apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-stylish-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-stylish-app
  template:
    metadata:
      labels:
        app: my-stylish-app
    spec:
      containers:
      - name: my-stylish-app-container
        image: ghcr.io/vitalisn4/my-stylish-app:mbiti2
        ports:
        - containerPort: 8080
        # env:
        # - name: API_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: my-stylish-app-secret 
        #       key: API_KEY
        envFrom:
        - configMapRef:
            name: my-stylish-app-config
        - secretRef:
            name: my-stylish-app-secret
