apiVersion: v1
kind: Service
metadata:
  name: my-stylish-app-service
spec:
  type: NodePort
  selector:
    app: my-stylish-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
