name: automated package push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    env:
      GITHUB_ACTOR: vitalis

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set lowercase variables
        id: vars
        run: |
          echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          echo "REPO_NAME_LC=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
          echo "ACTOR_LC=${GITHUB_ACTOR,,}" >> $GITHUB_ENV

      - name: login to container registry
        uses: docker/login-action@v2
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/${{ env.REPO_NAME_LC }}:latest
            ghcr.io/${{ env.REPO_OWNER_LC }}/${{ env.REPO_NAME_LC }}:${{ env.ACTOR_LC }}